name: Build and Test (Windows)
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/*.dll
