name: Test (Linux)
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v1
      - name: Test with Meson
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
